# Generated by Django 4.2.3 on 2023-07-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="prdDesc",
            field=models.TextField(),
        ),
    ]
