# Generated by Django 4.2.3 on 2023-07-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_product_prddesc_alter_product_prdname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="prdCost",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Cost"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="prdCreated",
            field=models.DateTimeField(verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="product",
            name="prdPrice",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Price"
            ),
        ),
    ]
