# Generated by Django 4.2.3 on 2023-07-29 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="catParent",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"catParent__isnull": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.category",
            ),
        ),
    ]
