# Generated by Django 4.2.3 on 2023-07-29 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_productaccessories_delete_productalternatives"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAlternatives",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "altAlternatives",
                    models.ManyToManyField(
                        related_name="Product_Alternatives", to="product.product"
                    ),
                ),
                (
                    "altProduct",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="main_Product",
                        to="product.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alternative",
                "verbose_name_plural": "Alternatives",
            },
        ),
    ]
