# Generated by Django 4.2.3 on 2023-07-29 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_productalternatives"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="catDesc",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="category",
            name="catImg",
            field=models.ImageField(upload_to="category/", verbose_name="Image"),
        ),
        migrations.AlterField(
            model_name="category",
            name="catName",
            field=models.CharField(max_length=80, verbose_name="Category Name"),
        ),
        migrations.AlterField(
            model_name="category",
            name="catParent",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"catParent__isnull": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.category",
                verbose_name="Main Category",
            ),
        ),
        migrations.AlterField(
            model_name="productaccessories",
            name="accAccessories",
            field=models.ManyToManyField(
                related_name="Product_accessories",
                to="product.product",
                verbose_name="Accessories",
            ),
        ),
        migrations.AlterField(
            model_name="productaccessories",
            name="accProduct",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_product",
                to="product.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="productalternatives",
            name="altAlternatives",
            field=models.ManyToManyField(
                related_name="Product_Alternatives",
                to="product.product",
                verbose_name="Alternatives",
            ),
        ),
        migrations.AlterField(
            model_name="productalternatives",
            name="altProduct",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_Product",
                to="product.product",
                verbose_name="Product",
            ),
        ),
    ]
