# Generated by Django 4.2.3 on 2023-07-29 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0010_alter_category_catdesc_alter_category_catimg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="prdCategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.category",
            ),
        ),
    ]
