# Generated by Django 4.2.3 on 2023-07-29 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
        ("product", "0011_product_prdcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="prdBrand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="settings.brand",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="prdVariant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="settings.variant",
            ),
        ),
    ]
