# Generated by Django 4.2.3 on 2023-07-29 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0012_product_prdbrand_product_prdvariant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="prdVariant",
        ),
    ]
